server:
  port: ${PORT:8081}

spring:
    application:
      name: Product-api

    main:
      allow-circular-references: true

    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/product-db
      username: admin
      password: 123456
      init-mode: always
      initialize: true
      continue-on-error: true
      maxActive: 3

    jpa:
      hibernate:
        ddl-auto: create-drop
      format-sql: true
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
